### ISSUE TITLE
AutoEnvPostProcessor注解在单元测试中不起作用

### ISSUE THREAD

**Issue by loaferframework** [lets-mica/mica-auto#4]
Please answer some questions before submitting your issue. Thanks!

### Which version of Mica do you using（使用的 mica 版本）?
2.0.4
### Expected behavior（预期的效果）
使用AutoEnvPostProcessor注解了一个实现了EnvironmentPostProcessor类，单元测试可以自动配置它
### Actual behavior（实际的效果）
打包可以生成spring.factories，但是单元测试无法自动配置
### Steps to reproduce the behavior（重现步骤）
1. maven依赖xml
```xml
<dependency>
    <groupId>net.dreamlu</groupId>
    <artifactId>mica-auto</artifactId>
    <scope>provided</scope>
</dependency>
```
2. 定义一个类实现EnvironmentPostProcessor，并注解@AutoEnvPostProcessor
3. 为实现类使用SpringBootTest写单元测试代码，并运行单元测试
### Other information（其他信息）
去掉依赖和注解，将maven package打包后生成的spring.factories文件拷贝到项目中，单元测试就没问题
看到maven的编译目录target文件夹classes中的spring.factories中的配置是正确的，但是test-classes中没有spring.factories

**Comment by ChunMengLu** [comment]
这个问题应该是已知问题（偶发），之前遇到是在多模块的情况下，依赖里了一个 maven 模块，模块里用到了 mica-auto。

另外 idea 也建议不要在一个窗口以多个模块打开多个项目，之前也踩过坑。

我抽空看看能不能解决（优先级不是很高，请注意）。

**Comment by ChunMengLu** [comment]
![image](https://user-images.githubusercontent.com/2115440/104902389-aced8080-59b9-11eb-811f-6d16dd2b8a17.png)

我这边没有复现，spring.factories 正常的生成到了 `target\classes\META-INF\spring.factories`。

你可以按我截图那样，`debug`  **mica-auto** 。

**Comment by loaferframework** [comment]
确实是我这边的问题，谢谢！
