### ISSUE TITLE
spring.factories自动添加的@Mapper导致报错Specified class is an interface

### ISSUE THREAD

**Issue by beetsuan** [lets-mica/mica-auto#5]
### Which version of Mica do you using（使用的 mica 版本）?
<mica-auto.version>2.3.0</mica-auto.version>
<springboot.version>2.7.0</springboot.version>
### Expected behavior（预期的效果）

mica-auto它默认把模块中所有@Component、@Service、@Controller、@Component、@Mapper等都给生成到spring.factories中去了，有咩有办法不单独给每个不需要的类加注解@AutoIgnore而是实现忽略功能，因为不忽略好像让Mapper接口被重复注册而报错，Failed to instantiate [***.mapper.RoleMapper]: Specified class is an interface.

**Comment by ChunMengLu** [comment]
1. mica-auto 是为 starter 设计的。
2. 你 `@Mapper` 上难道注入了 `@Component` 组合注解？？？

你这个是子模块？？？感觉 mica-auto 不适合你这个场景。你这个子模块的把包名设计好，能被扫描到就ok。

**Comment by beetsuan** [comment]
> 1. mica-auto 是为 starter 设计的。
> 2. 你 `@Mapper` 上难道注入了 `@Component` 组合注解？？？
> 
> 你这个是子模块？？？感觉 mica-auto 不适合你这个场景。你这个子模块的把包名设计好，能被扫描到就ok。

嗯呢，我还是把配置类抽取到starter中去吧，只扫starter就没问题了，感谢
