### ISSUE TITLE
简单感谢

### ISSUE THREAD

**Issue by yingzhuo** [lets-mica/mica-auto#6]
我用了您编写的工具，我司的starter文件做新旧兼容就简单多了，要不然维护两份确实麻烦。

**Comment by ChunMengLu** [comment]
感谢支持！！！

mica-auto 的初衷就是因为之前在理想汽车维护了一些 starter，偶尔改了 java 类忘记修改 `spring.factories` 没测试到位的话到项目运行的时候才能发现。

目前 mica-auto 已经迭代 3 年多。在 mica 、pig、SpringBlade 的一些生态中使用良好。
