### ISSUE TITLE
关于spring.factories的生成时机

### ISSUE THREAD

**Issue by jimmy384** [lets-mica/mica-auto#7]
1.定义了一个类，没有@Configuration，idea启动Application
```java
public class MyConfiguration {
}
```
自动生成的spring.factories没有MyConfiguration

2.添加@Configuration，idea启动Application
```java
@Configuration
public class MyConfiguration {
}
```
自动生成的spring.factories刷新了，有MyConfiguration

3.注释掉@Configuration，idea启动Application
```java
//@Configuration
public class MyConfiguration {
}
```
自动生成的spring.factories没变化，还是有MyConfiguration，行为不对

用命令行编译肯定是没问题的，但是结合idea使用的时候怎么保证每次频繁的修改能及时反馈到target目录(gradle的build目录)的spring.factories？

测试下来是不行的

**Comment by ChunMengLu** [comment]
> 1.定义了一个类，没有@configuration，idea启动Application
> 
> ```java
> public class MyConfiguration {
> }
> ```
> 
> 自动生成的spring.factories没有MyConfiguration
> 
> 2.添加@configuration，idea启动Application
> 
> ```java
> @Configuration
> public class MyConfiguration {
> }
> ```
> 
> 自动生成的spring.factories刷新了，有MyConfiguration
> 
> 3.注释掉@configuration，idea启动Application
> 
> ```java
> //@Configuration
> public class MyConfiguration {
> }
> ```
> 
> 自动生成的spring.factories没变化，还是有MyConfiguration，行为不对
> 
> 用命令行编译肯定是没问题的，但是结合idea使用的时候怎么保证每次频繁的修改能及时反馈到target目录(gradle的build目录)的spring.factories？
> 
> 测试下来是不行的

有时候受限于 idea 等开发工具规则，所以建议尽量只是在 stater 中使用，保证构建打包成 jar 发布时含有即可：

https://gitee.com/596392912/mica-auto/issues/I4193Q
